const drinksCatalog = {
  Лимонады: [
    {
      id: 'drink-lemonade-kiwi-lemon',
      name: 'Киви-лимон',
      description: null,
      image: 'assets/drinks/lemonades/kiwi-lemon.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
    {
      id: 'drink-lemonade-mango-passionfruit',
      name: 'Манго-маракуйя',
      description: null,
      image: 'assets/drinks/lemonades/mango-passionfruit.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
    {
      id: 'drink-lemonade-mojito',
      name: 'Мохито классический/клубничный',
      description: null,
      image: 'assets/drinks/lemonades/mojito.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
    {
      id: 'drink-lemonade-citrus',
      name: 'Цитрусовый',
      description: null,
      image: 'assets/drinks/lemonades/citrus.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
    {
      id: 'drink-lemonade-pina-colada',
      name: 'Пина колада',
      description: null,
      image: 'assets/drinks/lemonades/pina-colada.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
    {
      id: 'drink-lemonade-forest-berries',
      name: 'Лесные ягоды',
      description: null,
      image: 'assets/drinks/lemonades/forest-berries.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
    {
      id: 'drink-lemonade-cucumber',
      name: 'Огуречный',
      description: null,
      image: 'assets/drinks/lemonades/cucumber.webp',
      variants: [
        { measure: '400 мл', price: 400 },
        { measure: '1000 мл', price: 800 },
      ],
    },
  ],

  Коктейли: [
    {
      id: 'drink-cocktail-basil-smash',
      name: 'Бэзил Смэш',
      description: 'Джин, сахарный сироп, базилик, белок',
      measure: '400 мл',
      price: 500,
      image: 'assets/sample-basil-centered.webp',
    },
    {
      id: 'drink-cocktail-tropical-insolence',
      name: 'Тропическая наглость',
      description: 'Белый ром, кокосовый ликёр, ананасовый сок, Блю Кюрасао, сок лайма',
      measure: '300 мл',
      price: 650,
      image: 'assets/drinks/cocktails/tropical-insolence.webp',
    },
    {
      id: 'drink-cocktail-spring-vibe',
      name: 'Спринг Вайб',
      description: 'Банановый милкшейк, малиновое пюре, кокосовый сироп, ром',
      measure: '300 мл',
      price: 650,
      image: 'assets/drinks/cocktails/spring-vibe.webp',
    },
    {
      id: 'drink-cocktail-green-fairy',
      name: 'Зеленая фея',
      description: 'Водка, белый ром, серебряная текила, абсент, апельсиновый ликёр трипл-сек, Блю Кюрасао, сироп дыни, лимонный сок, энергетик',
      measure: '300 мл',
      price: 750,
      image: 'assets/drinks/cocktails/green-fairy.webp',
    },
    {
      id: 'drink-cocktail-pornstar-martini',
      name: 'Порнстар Мартини',
      description: 'Водка, игристое, сироп маракуйи, сироп ванили, лимонный сок',
      measure: '300 мл',
      price: 650,
      image: 'assets/sample-pornstar-centered.webp',
    },
    {
      id: 'drink-cocktail-kiwi-rum',
      name: 'Киви-ром',
      description: 'Белый ром, пюре киви, лимонный сок, сироп дыни',
      measure: '400 мл',
      price: 600,
      image: 'assets/drinks/cocktails/kiwi-rum.webp',
    },
    {
      id: 'drink-cocktail-gin-tonic',
      name: 'Джин-тоник',
      description: 'Джин, тоник',
      measure: '400 мл',
      price: 500,
      image: 'assets/drinks/cocktails/gin-tonic.webp',
    },
    {
      id: 'drink-cocktail-rum-mojito',
      name: 'Мохито с ромом классический',
      description: 'Белый ром, мята, лайм, минеральная вода, сахарный сироп',
      measure: '400 мл',
      price: 600,
      image: 'assets/drinks/cocktails/rum-mojito.webp',
    },
    {
      id: 'drink-cocktail-rum-mojito-strawberry',
      name: 'Мохито с ромом клубничный',
      description: 'Белый ром, мята, лайм, минеральная вода, сахарный сироп, пюре клубники',
      measure: '400 мл',
      price: 600,
      image: 'assets/drinks/cocktails/rum-mojito-strawberry.webp',
    },
    {
      id: 'drink-cocktail-lavender-lily',
      name: 'Лавандовая Лили',
      description: 'Сироп лаванды, трипл-сек, джин, лимонный фреш, белок',
      measure: '300 мл',
      price: 500,
      image: 'assets/drinks/cocktails/lavender-lily.webp',
    },
    {
      id: 'drink-cocktail-raspberry-martini',
      name: 'Малиновый мартини',
      description: 'Малиновое пюре, Мартини Фиеро, водка',
      measure: '300 мл',
      price: 550,
      image: 'assets/drinks/cocktails/raspberry-martini.webp',
    },
    {
      id: 'drink-cocktail-playboy',
      name: 'Плейбой',
      description: 'Белый ром, кокосовый ликёр, сливки, ананасовый сок',
      measure: '300 мл',
      price: 550,
      image: 'assets/drinks/cocktails/playboy.webp',
    },
    {
      id: 'drink-cocktail-ice-cherry-spritz',
      name: 'Айс Черри Спритц',
      description: 'Апероль, вишнёвый сок, шампанское брют',
      measure: '300 мл',
      price: 650,
      image: 'assets/drinks/cocktails/ice-cherry-spritz.webp',
    },
    {
      id: 'drink-cocktail-polar-bear',
      name: 'Полярный медведь',
      description: 'Сливки, бейлис, ром, кофейный ликёр',
      measure: '400 мл',
      price: 600,
      image: 'assets/drinks/cocktails/polar-bear.webp',
    },
    {
      id: 'drink-cocktail-orange-power',
      name: 'Орандж Пауэр',
      description: 'Егермейстер, ром, сливки, лимонный фреш, миндальный сироп',
      measure: '400 мл',
      price: 650,
      image: 'assets/drinks/cocktails/orange-power.webp',
    },
    {
      id: 'drink-cocktail-negroni',
      name: 'Негрони',
      description: 'Джин, кампари, мартини Россо',
      measure: '300 мл',
      price: 700,
      image: 'assets/sample-negroni-centered.webp',
    },
    {
      id: 'drink-cocktail-mai-tai',
      name: 'Май Тай',
      description: 'Амаретто, белый ром, тёмный ром, миндальный сироп, апельсиновый сок, ананасовый сок',
      measure: '400 мл',
      price: 750,
      image: 'assets/drinks/cocktails/mai-tai.webp',
    },
    {
      id: 'drink-cocktail-cranberry-long-island',
      name: 'Клюквенный Лонг Айленд',
      description: 'Трипл-сек, джин, текила сильвер, белый ром, водка, лимонный фреш, клюквенный морс',
      measure: '400 мл',
      price: 850,
      image: 'assets/drinks/cocktails/cranberry-long-island.webp',
    },
  ],

  Шоты: [
    { id: 'drink-shot-b52', name: 'Б-52', description: 'Кофейный ликёр, Бейлис, трипл-сек', measure: '45 мл', price: 500, image: null },
    { id: 'drink-shot-b53', name: 'Б-53', description: 'Кофейный ликёр, Бейлис, абсент', measure: '45 мл', price: 500, image: null },
    { id: 'drink-shot-medusa', name: 'Медуза', description: 'Ром, трипл-сек, Бейлис, Блю Кюрасао, кокосовый ликёр', measure: '45 мл', price: 500, image: null },
    { id: 'drink-shot-green-mexican', name: 'Зеленый мексиканец', description: 'Текила, сироп «Зеленая дыня», лимонный сок', measure: '45 мл', price: 500, image: null },
    { id: 'drink-shot-uncle-vanya', name: 'Дядя Ваня', description: 'Водка, гранатовый сироп, лимонный сок', measure: '45 мл', price: 500, image: null },
    { id: 'drink-shot-sambuca', name: 'Самбука', description: 'Поджигается', measure: '40 мл', price: 500, image: null },
  ],

  Смузи: [
    {
      id: 'drink-smoothie-berries',
      name: 'Клубника-Малина-Ежевика',
      description: 'Клубника, малина, ежевика, сахар',
      measure: '400 мл',
      price: 450,
      image: 'assets/drinks/smoothies/strawberry-raspberry-blackberry.webp',
    },
    {
      id: 'drink-smoothie-strawberry-banana',
      name: 'Клубника-банан',
      description: 'Клубника, банан',
      measure: '400 мл',
      price: 450,
      image: 'assets/drinks/smoothies/strawberry-banana.webp',
    },
    {
      id: 'drink-smoothie-kiwi-apple',
      name: 'Киви-яблоко',
      description: 'Киви, яблоко, сахар',
      measure: '400 мл',
      price: 450,
      image: 'assets/drinks/smoothies/kiwi-apple.webp',
    },
    {
      id: 'drink-smoothie-green',
      name: 'Зеленый смузи',
      description: 'Ананас, щавель, ананасовый сок',
      measure: '400 мл',
      price: 450,
      image: 'assets/drinks/smoothies/green.webp',
    },
  ],

  Кофе: [
    { id: 'drink-coffee-espresso', name: 'Эспрессо', description: null, measure: null, price: 150, image: 'assets/drinks/coffee/espresso.webp' },
    { id: 'drink-coffee-americano', name: 'Американо', description: null, measure: null, price: 200, image: 'assets/drinks/coffee/americano.webp' },
    { id: 'drink-coffee-cappuccino', name: 'Капучино', description: null, measure: null, price: 250, image: 'assets/drinks/coffee/cappuccino.webp' },
    { id: 'drink-coffee-latte', name: 'Латте', description: null, measure: null, price: 270, image: 'assets/drinks/coffee/latte.webp' },
    { id: 'drink-coffee-flat-white', name: 'Флэт Уайт', description: null, measure: null, price: 250, image: 'assets/drinks/coffee/flat-white.webp' },
    { id: 'drink-coffee-bumble', name: 'Бамбл', description: null, measure: null, price: 300, image: 'assets/drinks/coffee/bumble.webp' },
    { id: 'drink-coffee-iced-latte', name: 'Айс латте', description: null, measure: null, price: 300, image: 'assets/drinks/coffee/iced-latte.webp' },
    { id: 'drink-coffee-espresso-tonic', name: 'Эспрессо-тоник', description: null, measure: null, price: 300, image: 'assets/drinks/coffee/espresso-tonic.webp' },
  ],

  Чай: [
    { id: 'drink-tea-green', name: 'Зеленый', description: null, measure: '1000 мл', price: 400, image: null },
    { id: 'drink-tea-black', name: 'Черный', description: null, measure: '1000 мл', price: 400, image: null },
    { id: 'drink-tea-bergamot', name: 'Черный с бергамотом', description: null, measure: '1000 мл', price: 400, image: null },
    { id: 'drink-tea-orange', name: 'Черный с апельсином', description: null, measure: '1000 мл', price: 400, image: null },
    { id: 'drink-tea-wild-cherry', name: 'Дикая вишня', description: null, measure: '1000 мл', price: 400, image: null },
    { id: 'drink-tea-mountain', name: 'Горный', description: null, measure: '1000 мл', price: 400, image: null },
  ],

  'Авторский чай': [
    {
      id: 'drink-author-tea-tropical',
      name: 'Тропический',
      description: 'Зеленый чай, пюре манго, лимон, сироп маракуйи, ананасовый сок, ананас',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/tropical.webp',
    },
    {
      id: 'drink-author-tea-thai',
      name: 'Тайский',
      description: 'Чай анчан, лимон, сироп лаванды, сироп Блю Кюрасао, апельсиновый сок',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/thai.webp',
    },
    {
      id: 'drink-author-tea-currant-basil',
      name: 'Смородина-базилик',
      description: 'Пюре смородины, мята, базилик, чай «Дикая вишня»',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/currant-basil.webp',
    },
    {
      id: 'drink-author-tea-citrus',
      name: 'Цитрусовый',
      description: 'Лимон, апельсин, апельсиновый сок, мята, чай «Апельсин-корица»',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/citrus.webp',
    },
    {
      id: 'drink-author-tea-vitamin',
      name: 'Витаминный',
      description: 'Имбирь, апельсин, лимон, мед',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/vitamin.webp',
    },
    {
      id: 'drink-author-tea-sea-buckthorn',
      name: 'Облепиховый',
      description: 'Облепиха, мед',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/sea-buckthorn.webp',
    },
    {
      id: 'drink-author-tea-raspberry',
      name: 'Малиновый',
      description: 'Малиновое пюре, малина, лимон, мята',
      measure: '1000 мл',
      price: 550,
      image: 'assets/drinks/author-tea/raspberry.webp',
    },
  ],

  'Безалкогольные напитки': [
    { id: 'drink-soft-borjomi', name: 'Боржоми', description: null, measure: '500 мл', price: 300, image: null },
    { id: 'drink-soft-water', name: 'Вода', description: null, measure: '500 мл', price: 200, image: null },
    { id: 'drink-soft-fanta', name: 'Фанта', description: null, measure: '330 мл', price: 250, image: null },
    { id: 'drink-soft-sprite', name: 'Спрайт', description: null, measure: '330 мл', price: 250, image: null },
    { id: 'drink-soft-cola', name: 'Кола', description: null, measure: '330 мл', price: 250, image: null },
    { id: 'drink-soft-red-bull', name: 'Ред Булл', description: null, measure: '250 мл', price: 350, image: null },
    {
      id: 'drink-soft-juice',
      name: 'Сок в ассортименте',
      description: null,
      image: null,
      variants: [
        { measure: '200 мл', price: 250 },
        { measure: '1000 мл', price: 500 },
      ],
    },
  ],

  Пиво: [
    { id: 'drink-beer-stella-artois', name: 'Стелла Артуа', description: null, measure: '500 мл', price: 350, image: null },
    { id: 'drink-beer-bud', name: 'Бад', description: null, measure: '450 мл', price: 300, image: null },
    { id: 'drink-beer-corona-extra', name: 'Корона Экстра', description: null, measure: '330 мл', price: 450, image: null },
  ],

  Джин: [
    { id: 'drink-gin-barrister', name: 'Барристер', description: null, measure: '40 мл', price: 200, image: null },
    { id: 'drink-gin-beefeater', name: 'Бифитер', description: null, measure: '40 мл', price: 400, image: null },
  ],

  Текила: [
    { id: 'drink-tequila-olmeca-gold', name: 'Ольмека Голд', description: null, measure: '40 мл', price: 400, image: null },
    { id: 'drink-tequila-olmeca-silver', name: 'Ольмека Сильвер', description: null, measure: '40 мл', price: 500, image: null },
  ],

  Водка: [
    { id: 'drink-vodka-tsarskaya-original', name: 'Царская Оригинальная', description: null, measure: '40 мл', price: 250, image: null },
    { id: 'drink-vodka-tsarskaya-gold', name: 'Царская Золотая', description: null, measure: '40 мл', price: 270, image: null },
    { id: 'drink-vodka-beluga', name: 'Белуга', description: null, measure: '40 мл', price: 350, image: null },
    { id: 'drink-vodka-chistye-rosy', name: 'Чистые Росы', description: null, measure: '40 мл', price: 380, image: null },
  ],

  Шампанское: [
    { id: 'drink-sparkling-abrau-semisweet', name: 'Абрау-Дюрсо белое полусладкое', brandLine: 'Абрау-Дюрсо', typeLine: 'Белое полусладкое', description: null, measure: null, price: 1700, image: null },
    { id: 'drink-sparkling-abrau-semidry', name: 'Абрау-Дюрсо белое полусухое', brandLine: 'Абрау-Дюрсо', typeLine: 'Белое полусухое', description: null, measure: null, price: 1700, image: null },
    { id: 'drink-sparkling-abrau-brut', name: 'Абрау-Дюрсо брют', brandLine: 'Абрау-Дюрсо', typeLine: 'Брют', description: null, measure: null, price: 1700, image: null },
    { id: 'drink-sparkling-golitsyn-semisweet', name: 'Лев Голицынъ белое полусладкое', brandLine: 'Лев Голицынъ', typeLine: 'Белое полусладкое', description: null, measure: null, price: 1700, image: null },
    { id: 'drink-sparkling-golitsyn-semidry', name: 'Лев Голицынъ белое полусухое', brandLine: 'Лев Голицынъ', typeLine: 'Белое полусухое', description: null, measure: null, price: 1700, image: null },
    { id: 'drink-sparkling-golitsyn-brut', name: 'Лев Голицынъ брют', brandLine: 'Лев Голицынъ', typeLine: 'Брют', description: null, measure: null, price: 1700, image: null },
  ],

  Вино: [
    {
      id: 'drink-wine-trozo-red-dry',
      name: 'ТРОЗО красное сухое',
      brandLine: 'ТРОЗО',
      typeLine: 'Красное сухое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 300 },
        { measure: '750 мл', price: 1500 },
      ],
    },
    {
      id: 'drink-wine-trozo-red-semisweet',
      name: 'ТРОЗО красное полусладкое',
      brandLine: 'ТРОЗО',
      typeLine: 'Красное полусладкое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 300 },
        { measure: '750 мл', price: 1500 },
      ],
    },
    {
      id: 'drink-wine-trozo-white-dry',
      name: 'ТРОЗО белое сухое',
      brandLine: 'ТРОЗО',
      typeLine: 'Белое сухое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 300 },
        { measure: '750 мл', price: 1500 },
      ],
    },
    {
      id: 'drink-wine-trozo-white-semisweet',
      name: 'ТРОЗО белое полусладкое',
      brandLine: 'ТРОЗО',
      typeLine: 'Белое полусладкое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 300 },
        { measure: '750 мл', price: 1500 },
      ],
    },
    {
      id: 'drink-wine-tsinandali',
      name: 'Цинандали белое сухое',
      brandLine: 'Цинандали',
      typeLine: 'Белое сухое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 400 },
        { measure: '750 мл', price: 2000 },
      ],
    },
    {
      id: 'drink-wine-saperavi',
      name: 'Саперави красное сухое',
      brandLine: 'Саперави',
      typeLine: 'Красное сухое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 400 },
        { measure: '750 мл', price: 2000 },
      ],
    },
    {
      id: 'drink-wine-alazani-valley',
      name: 'Алазанская долина красное полусладкое',
      brandLine: 'Алазанская долина',
      typeLine: 'Красное полусладкое',
      description: null,
      image: null,
      variants: [
        { measure: '150 мл', price: 400 },
        { measure: '750 мл', price: 2000 },
      ],
    },
  ],

  Коньяк: [
    { id: 'drink-cognac-old-kakheti', name: 'Старый Кахети', stars: 3, description: null, measure: '40 мл', price: 300, image: null },
    { id: 'drink-cognac-ararat-three', name: 'Арарат', stars: 3, description: null, measure: '40 мл', price: 400, image: null },
    { id: 'drink-cognac-ararat-five', name: 'Арарат', stars: 5, description: null, measure: '40 мл', price: 450, image: null },
    { id: 'drink-cognac-hennessy', name: 'Хеннесси', description: null, measure: '40 мл', price: 700, image: null },
  ],

  Виски: [
    { id: 'drink-whiskey-jameson', name: 'Джеймсон', description: null, measure: '40 мл', price: 550, image: null },
    { id: 'drink-whiskey-chivas', name: 'Чивас', description: null, measure: '40 мл', price: 600, image: null },
    { id: 'drink-whiskey-monkey-shoulder', name: 'Манки Шолдер', description: null, measure: '40 мл', price: 600, image: null },
    { id: 'drink-whiskey-jack-daniels', name: 'Джек Дэниелс', description: null, measure: '40 мл', price: 550, image: null },
  ],
};
